# Organize LH sample for PR poly LHS multistart

In [1]:
import pandas as pd
import numpy as np

import sys
sys.path.append('../../')

In [2]:
SRK_quad_results = pd.read_csv('Final_Results/Data/Init_Final/LHS_Output/SRK_quadTdep_LHS_final.csv',index_col=0)

In [3]:
SRK_quad_results.dropna(axis=0)

,Param1,Param2,Param3,Param4,Param5,Param6,sc_param1,sc_param2,sc_param3,sc_param4,sc_param5,sc_param6,"SRK_kappa_A[bmimpf6,R32]","SRK_kappa_A[R32,bmimpf6]","SRK_kappa_B[bmimpf6,R32]","SRK_kappa_B[R32,bmimpf6]","SRK_kappa_C[bmimpf6,R32]","SRK_kappa_C[R32,bmimpf6]",SSR
1501,0.375854,0.647447,0.573016,0.094414,0.485069,0.750320,-0.496796,0.589789,0.292200,-1.622518,-0.059634,1.001379,1.555715,0.697419,-1.604866,-1.292496,-0.037172,0.558732,8.302788
4398,0.766436,0.034984,0.113285,0.797132,0.629490,0.661523,1.066078,-1.860413,-1.546932,1.188840,0.518076,0.646139,-8.770646,-6.525781,12.938465,12.177787,-3.856781,-5.668545,826.909660

In [4]:
quad = SRK_quad_results.iloc[1501]

In [5]:
lhs = pd.read_csv('../../LHS_5000x8.txt')

In [6]:
lhs['sc_param7'] = ((lhs['Param7']-lhs['Param7'].min())/(lhs['Param7'].max()-lhs['Param7'].min()))*4+(-2)
lhs['sc_param8'] = ((lhs['Param8']-lhs['Param8'].min())/(lhs['Param8'].max()-lhs['Param8'].min()))*4+(-2)

In [7]:
quad_sc = quad[['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6']]
# quad_227_act = quad_227[['PR_kappa_A[emimTf2N,R32]','PR_kappa_A[R32,emimTf2N]','PR_kappa_B[emimTf2N,R32]','PR_kappa_B[R32,emimTf2N]','PR_kappa_C[emimTf2N,R32]','PR_kappa_C[R32,emimTf2N]']]

In [8]:
quad_sc_df = pd.DataFrame(quad_sc).T
sc = pd.concat([quad_sc_df]*5000,ignore_index=True)
sc_lhs = pd.concat([sc,lhs[['sc_param7','sc_param8']]],axis=1,ignore_index=True)
sc_lhs.columns = ['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6','sc_param7','sc_param8']
sc_lhs.to_csv('Final_Results/Data/Init_Final/SRK_polyTdep_LHS_fromquad.csv',sep=',')

In [9]:
# quad_227_act_df = pd.DataFrame(quad_227_act).T
# quad_227_act_df.columns = ['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6']
# act = pd.concat([quad_227_act_df]*250,ignore_index=True)
# act_lhs = pd.concat([act,lhs[['sc_param7','sc_param8']]],axis=1,ignore_index=True)
# act_lhs.columns = ['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6','sc_param7','sc_param8']
# act_lhs.to_csv('Data/Fits/LHS_Fits/PR_polyTdep_actLHS.csv',sep=',')

In [10]:
sc_lhs

,sc_param1,sc_param2,sc_param3,sc_param4,sc_param5,sc_param6,sc_param7,sc_param8
0,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,-1.864270,-0.490373
1,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,0.451423,1.493513
2,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,0.420224,1.786663
3,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,-1.564046,0.398068
4,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,1.236035,0.181794
...,...,...,...,...,...,...,...,...
4995,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,1.396730,-1.402362
4996,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,0.032425,0.673016
4997,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,-0.288545,-0.892166
4998,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,0.104533,0.399640
4999,-0.496796,0.589789,0.2922,-1.622518,-0.059634,1.001379,1.036576,1.555110