# Organize LH sample for SRK poly LHS multistart

In [1]:
import pandas as pd
import numpy as np

import sys
sys.path.append('../../')

In [2]:
SRK_quad_results = pd.read_csv('Final_Results/Data/Init_Final/LHS_Output/SRK_quadTdep_LHS_final.csv',index_col=0)

In [3]:
SRK_quad_results.dropna(axis=0)

,Param1,Param2,Param3,Param4,Param5,Param6,sc_param1,sc_param2,sc_param3,sc_param4,sc_param5,sc_param6,"SRK_kappa_A[emimTf2N,R32]","SRK_kappa_A[R32,emimTf2N]","SRK_kappa_B[emimTf2N,R32]","SRK_kappa_B[R32,emimTf2N]","SRK_kappa_C[emimTf2N,R32]","SRK_kappa_C[R32,emimTf2N]",SSR
461,0.322917,0.558144,0.409933,0.246390,0.802685,0.715946,-0.708620,0.232525,-0.360206,-1.014511,1.210888,0.863863,0.678952,0.353652,-0.204431,-0.603068,-0.633878,0.199234,3.832085
1501,0.375854,0.647447,0.573016,0.094414,0.485069,0.750320,-0.496796,0.589789,0.292200,-1.622518,-0.059634,1.001379,0.678950,0.353652,-0.204428,-0.603068,-0.633879,0.199234,3.832085
2268,0.577432,0.069101,0.063235,0.746237,0.804114,0.671634,0.309795,-1.723929,-1.747158,0.985224,1.216606,0.686590,-4.286877,-4.891288,0.945388,8.793227,3.615844,-3.946729,1332.988528
3196,0.219315,0.052459,0.172854,0.901598,0.970125,0.539986,-1.123173,-1.790506,-1.308630,1.606775,1.880680,0.159922,0.678948,0.353652,-0.204423,-0.603068,-0.633882,0.199234,3.832082
3319,0.080298,0.188618,0.844589,0.755908,0.535566,0.532437,-1.679435,-1.245789,1.378619,1.023912,0.142361,0.129719,-2.419571,-5.365588,-2.172765,9.640407,4.831520,-4.324595,1161.717921
3509,0.094904,0.350023,0.228243,0.142143,0.783457,0.936461,-1.620993,-0.600077,-1.087049,-1.431569,1.133974,1.746051,2.415483,-4.012415,-13.171266,7.322814,11.041713,-3.344359,3627.643593
3534,0.613879,0.048818,0.229303,0.452727,0.849661,0.895539,0.455636,-1.805071,-1.082809,-0.189018,1.398800,1.582340,-0.541960,-9.159188,-9.022289,16.189403,9.366453,-7.177065,3024.049207
3964,0.385865,0.054794,0.138114,0.418697,0.864634,0.926236,-0.456740,-1.781164,-1.447604,-0.325163,1.458696,1.705142,5.891847,-5.677927,-19.999995,10.066387,14.234016,-4.480879,3403.346271
4123,0.457181,0.069687,0.098625,0.412596,0.661289,0.907472,-0.171374,-1.721584,-1.605580,-0.349570,0.645276,1.630075,5.604294,-6.401125,-19.999996,11.328308,14.485739,-5.029451,3482.550608
4475,0.340152,0.018430,0.548103,0.617827,0.507984,0.847794,-0.639658,-1.926640,0.192540,0.471495,0.032027,1.391329,-4.295227,-8.406216,0.121069,14.817678,4.226542,-6.528652,1074.039788
4873,0.046049,0.045816,0.932074,0.806436,0.429535,0.628984,-1.816478,-1.817083,1.728598,1.226059,-0.281781,0.515963,-3.712128,-4.767195,0.148616,8.615089,3.853740,-3.884265,1392.276666

In [4]:
quad_3196 = SRK_quad_results.iloc[3196]

In [5]:
lhs = pd.read_csv('../../LHS_5000x8.txt')

In [6]:
lhs['sc_param7'] = ((lhs['Param7']-lhs['Param7'].min())/(lhs['Param7'].max()-lhs['Param7'].min()))*4+(-2)
lhs['sc_param8'] = ((lhs['Param8']-lhs['Param8'].min())/(lhs['Param8'].max()-lhs['Param8'].min()))*4+(-2)

In [8]:
quad_3196 = quad_3196[['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6']]

In [9]:
quad_3196_sc_df = pd.DataFrame(quad_3196).T
sc = pd.concat([quad_3196_sc_df]*5000,ignore_index=True)
sc_lhs = pd.concat([sc,lhs[['sc_param7','sc_param8']]],axis=1,ignore_index=True)
sc_lhs.columns = ['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6','sc_param7','sc_param8']
sc_lhs.to_csv('Final_Results/Data/Init_Final/SRK_polyTdep_fromquad_init.csv',sep=',')

In [10]:
sc_lhs

,sc_param1,sc_param2,sc_param3,sc_param4,sc_param5,sc_param6,sc_param7,sc_param8
0,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,-1.864270,-0.490373
1,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,0.451423,1.493513
2,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,0.420224,1.786663
3,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,-1.564046,0.398068
4,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,1.236035,0.181794
...,...,...,...,...,...,...,...,...
4995,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,1.396730,-1.402362
4996,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,0.032425,0.673016
4997,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,-0.288545,-0.892166
4998,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,0.104533,0.399640
4999,-1.123173,-1.790506,-1.30863,1.606775,1.88068,0.159922,1.036576,1.555110

In [ ]:
# quad_33_act_df = pd.DataFrame(quad_33_act).T
# quad_33_act_df.columns = ['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6']
# act = pd.concat([quad_33_act_df]*250,ignore_index=True)
# act_lhs = pd.concat([act,lhs[['sc_param7','sc_param8']]],axis=1,ignore_index=True)
# act_lhs.columns = ['sc_param1','sc_param2','sc_param3','sc_param4','sc_param5','sc_param6','sc_param7','sc_param8']
# act_lhs.to_csv('Data/Fits/LHS_Fits/SRK_polyTdep_actLHS.csv',sep=',')

In [ ]:
sc_lhs

In [ ]:
act_lhs